### ISSUE TITLE
Hi Ibnuda

### ISSUE THREAD

**Issue by rizary** [ibnuda/Libil#1]
Halo mas Ibnuda, artikel haskellnya keren banget. Kebetulan Saya lagi mau bangun komunitas Haskell di Indonesia. Saat ini Saya fokus di Haskell juga, so mungkin was bisa sharing2 ilmunya kepada teman2 yang baru belajar. Silahkan join disini ya mas:

t.me/haskell_id

Kalau sudah join atau tidak berkenan gabung, silahkan close issue ini ya mas.

Maaf Saya kesulitan untuk kontak mas. Sepertinya repo mas yang gitlab sulit Saya akses. And you know how our country treat Reddit right?

Best of luck for you,
Andika

**Comment by ibnuda** [comment]
Ok!
